__all__ = ('country_codes',)

country_codes = { # talk about ugly lol
    'oc':   1, 'eu':   2, 'ad':   3, 'ae':   4, 'af':   5, 'ag':   6, 'ai':   7,
    'al':   8, 'am':   9, 'an':  10, 'ao':  11, 'aq':  12, 'ar':  13, 'as':  14,
    'at':  15, 'au':  16, 'aw':  17, 'az':  18, 'ba':  19, 'bb':  20, 'bd':  21,
    'be':  22, 'bf':  23, 'bg':  24, 'bh':  25, 'bi':  26, 'bj':  27, 'bm':  28,
    'bn':  29, 'bo':  30, 'br':  31, 'bs':  32, 'bt':  33, 'bv':  34, 'bw':  35,
    'by':  36, 'bz':  37, 'ca':  38, 'cc':  39, 'cd':  40, 'cf':  41, 'cg':  42,
    'ch':  43, 'ci':  44, 'ck':  45, 'cl':  46, 'cm':  47, 'cn':  48, 'co':  49,
    'cr':  50, 'cu':  51, 'cv':  52, 'cx':  53, 'cy':  54, 'cz':  55, 'de':  56,
    'dj':  57, 'dk':  58, 'dm':  59, 'do':  60, 'dz':  61, 'ec':  62, 'ee':  63,
    'eg':  64, 'eh':  65, 'er':  66, 'es':  67, 'et':  68, 'fi':  69, 'fj':  70,
    'fk':  71, 'fm':  72, 'fo':  73, 'fr':  74, 'fx':  75, 'ga':  76, 'gb':  77,
    'gd':  78, 'ge':  79, 'gf':  80, 'gh':  81, 'gi':  82, 'gl':  83, 'gm':  84,
    'gn':  85, 'gp':  86, 'gq':  87, 'gr':  88, 'gs':  89, 'gt':  90, 'gu':  91,
    'gw':  92, 'gy':  93, 'hk':  94, 'hm':  95, 'hn':  96, 'hr':  97, 'ht':  98,
    'hu':  99, 'id': 100, 'ie': 101, 'il': 102, 'in': 103, 'io': 104, 'iq': 105,
    'ir': 106, 'is': 107, 'it': 108, 'jm': 109, 'jo': 110, 'jp': 111, 'ke': 112,
    'kg': 113, 'kh': 114, 'ki': 115, 'km': 116, 'kn': 117, 'kp': 118, 'kr': 119,
    'kw': 120, 'ky': 121, 'kz': 122, 'la': 123, 'lb': 124, 'lc': 125, 'li': 126,
    'lk': 127, 'lr': 128, 'ls': 129, 'lt': 130, 'lu': 131, 'lv': 132, 'ly': 133,
    'ma': 134, 'mc': 135, 'md': 136, 'mg': 137, 'mh': 138, 'mk': 139, 'ml': 140,
    'mm': 141, 'mn': 142, 'mo': 143, 'mp': 144, 'mq': 145, 'mr': 146, 'ms': 147,
    'mt': 148, 'mu': 149, 'mv': 150, 'mw': 151, 'mx': 152, 'my': 153, 'mz': 154,
    'na': 155, 'nc': 156, 'ne': 157, 'nf': 158, 'ng': 159, 'ni': 160, 'nl': 161,
    'no': 162, 'np': 163, 'nr': 164, 'nu': 165, 'nz': 166, 'om': 167, 'pa': 168,
    'pe': 169, 'pf': 170, 'pg': 171, 'ph': 172, 'pk': 173, 'pl': 174, 'pm': 175,
    'pn': 176, 'pr': 177, 'ps': 178, 'pt': 179, 'pw': 180, 'py': 181, 'qa': 182,
    're': 183, 'ro': 184, 'ru': 185, 'rw': 186, 'sa': 187, 'sb': 188, 'sc': 189,
    'sd': 190, 'se': 191, 'sg': 192, 'sh': 193, 'si': 194, 'sj': 195, 'sk': 196,
    'sl': 197, 'sm': 198, 'sn': 199, 'so': 200, 'sr': 201, 'st': 202, 'sv': 203,
    'sy': 204, 'sz': 205, 'tc': 206, 'td': 207, 'tf': 208, 'tg': 209, 'th': 210,
    'tj': 211, 'tk': 212, 'tm': 213, 'tn': 214, 'to': 215, 'tl': 216, 'tr': 217,
    'tt': 218, 'tv': 219, 'tw': 220, 'tz': 221, 'ua': 222, 'ug': 223, 'um': 224,
    'us': 225, 'uy': 226, 'uz': 227, 'va': 228, 'vc': 229, 've': 230, 'vg': 231,
    'vi': 232, 'vn': 233, 'vu': 234, 'wf': 235, 'ws': 236, 'ye': 237, 'yt': 238,
    'rs': 239, 'za': 240, 'zm': 241, 'me': 242, 'zw': 243, 'xx': 244, 'a2': 245,
    'o1': 246, 'ax': 247, 'gg': 248, 'im': 249, 'je': 250, 'bl': 251, 'mf': 252
}

short2long = {
    "AF":"Afghanistan",
    "AX":"Aland Islands",
    "AL":"Albania",
    "DZ":"Algeria",
    "AS":"American Samoa",
    "AD":"Andorra",
    "AO":"Angola",
    "AI":"Anguilla",
    "AQ":"Antarctica",
    "AG":"Antigua and Barbuda",
    "AR":"Argentina",
    "AM":"Armenia",
    "AW":"Aruba",
    "AU":"Australia",
    "AT":"Austria",
    "AZ":"Azerbaijan",
    "BS":"Bahamas",
    "BH":"Bahrain",
    "BD":"Bangladesh",
    "BB":"Barbados",
    "BY":"Belarus",
    "BE":"Belgium",
    "BZ":"Belize",
    "BJ":"Benin",
    "BM":"Bermuda",
    "BT":"Bhutan",
    "BO":"Bolivia, Plurinational State of",
    "BQ":"Bonaire, Sint Eustatius and Saba",
    "BA":"Bosnia and Herzegovina",
    "BW":"Botswana",
    "BV":"Bouvet Island",
    "BR":"Brazil",
    "IO":"British Indian Ocean Territory",
    "BN":"Brunei Darussalam",
    "BG":"Bulgaria",
    "BF":"Burkina Faso",
    "BI":"Burundi",
    "KH":"Cambodia",
    "CM":"Cameroon",
    "CA":"Canada",
    "CV":"Cape Verde",
    "KY":"Cayman Islands",
    "CF":"Central African Republic",
    "TD":"Chad",
    "CL":"Chile",
    "CN":"China",
    "CX":"Christmas Island",
    "CC":"Cocos (Keeling) Islands",
    "CO":"Colombia",
    "KM":"Comoros",
    "CG":"Congo",
    "CD":"Congo, The Democratic Republic of the",
    "CK":"Cook Islands",
    "CR":"Costa Rica",
    "CI":"Côte d'Ivoire",
    "HR":"Croatia",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CY":"Cyprus",
    "CZ":"Czech Republic",
    "DK":"Denmark",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DO":"Dominican Republic",
    "EC":"Ecuador",
    "EG":"Egypt",
    "SV":"El Salvador",
    "GQ":"Equatorial Guinea",
    "ER":"Eritrea",
    "EE":"Estonia",
    "ET":"Ethiopia",
    "FK":"Falkland Islands (Malvinas)",
    "FO":"Faroe Islands",
    "FJ":"Fiji",
    "FI":"Finland",
    "FR":"France",
    "GF":"French Guiana",
    "PF":"French Polynesia",
    "TF":"French Southern Territories",
    "GA":"Gabon",
    "GM":"Gambia",
    "GE":"Georgia",
    "DE":"Germany",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GR":"Greece",
    "GL":"Greenland",
    "GD":"Grenada",
    "GP":"Guadeloupe",
    "GU":"Guam",
    "GT":"Guatemala",
    "GG":"Guernsey",
    "GN":"Guinea",
    "GW":"Guinea-Bissau",
    "GY":"Guyana",
    "HT":"Haiti",
    "HM":"Heard Island and McDonald Islands",
    "VA":"Holy See (Vatican City State)",
    "HN":"Honduras",
    "HK":"Hong Kong",
    "HU":"Hungary",
    "IS":"Iceland",
    "IN":"India",
    "ID":"Indonesia",
    "IR":"Iran, Islamic Republic of",
    "IQ":"Iraq",
    "IE":"Ireland",
    "IM":"Isle of Man",
    "IL":"Israel",
    "IT":"Italy",
    "JM":"Jamaica",
    "JP":"Japan",
    "JE":"Jersey",
    "JO":"Jordan",
    "KZ":"Kazakhstan",
    "KE":"Kenya",
    "KI":"Kiribati",
    "KP":"Korea, Democratic People's Republic of",
    "KR":"Korea, Republic of",
    "KW":"Kuwait",
    "KG":"Kyrgyzstan",
    "LA":"Lao People's Democratic Republic",
    "LV":"Latvia",
    "LB":"Lebanon",
    "LS":"Lesotho",
    "LR":"Liberia",
    "LY":"Libya",
    "LI":"Liechtenstein",
    "LT":"Lithuania",
    "LU":"Luxembourg",
    "MO":"Macao",
    "MK":"Macedonia, Republic of",
    "MG":"Madagascar",
    "MW":"Malawi",
    "MY":"Malaysia",
    "MV":"Maldives",
    "ML":"Mali",
    "MT":"Malta",
    "MH":"Marshall Islands",
    "MQ":"Martinique",
    "MR":"Mauritania",
    "MU":"Mauritius",
    "YT":"Mayotte",
    "MX":"Mexico",
    "FM":"Micronesia, Federated States of",
    "MD":"Moldova, Republic of",
    "MC":"Monaco",
    "MN":"Mongolia",
    "ME":"Montenegro",
    "MS":"Montserrat",
    "MA":"Morocco",
    "MZ":"Mozambique",
    "MM":"Myanmar",
    "NA":"Namibia",
    "NR":"Nauru",
    "NP":"Nepal",
    "NL":"Netherlands",
    "NC":"New Caledonia",
    "NZ":"New Zealand",
    "NI":"Nicaragua",
    "NE":"Niger",
    "NG":"Nigeria",
    "NU":"Niue",
    "NF":"Norfolk Island",
    "MP":"Northern Mariana Islands",
    "NO":"Norway",
    "OM":"Oman",
    "PK":"Pakistan",
    "PW":"Palau",
    "PS":"Palestinian Territory, Occupied",
    "PA":"Panama",
    "PG":"Papua New Guinea",
    "PY":"Paraguay",
    "PE":"Peru",
    "PH":"Philippines",
    "PN":"Pitcairn",
    "PL":"Poland",
    "PT":"Portugal",
    "PR":"Puerto Rico",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Romania",
    "RU":"Russian Federation",
    "RW":"Rwanda",
    "BL":"Saint Barthélemy",
    "SH":"Saint Helena, Ascension and Tristan da Cunha",
    "KN":"Saint Kitts and Nevis",
    "LC":"Saint Lucia",
    "MF":"Saint Martin (French part)",
    "PM":"Saint Pierre and Miquelon",
    "VC":"Saint Vincent and the Grenadines",
    "WS":"Samoa",
    "SM":"San Marino",
    "ST":"Sao Tome and Principe",
    "SA":"Saudi Arabia",
    "SN":"Senegal",
    "RS":"Serbia",
    "SC":"Seychelles",
    "SL":"Sierra Leone",
    "SG":"Singapore",
    "SX":"Sint Maarten (Dutch part)",
    "SK":"Slovakia",
    "SI":"Slovenia",
    "SB":"Solomon Islands",
    "SO":"Somalia",
    "ZA":"South Africa",
    "GS":"South Georgia and the South Sandwich Islands",
    "ES":"Spain",
    "LK":"Sri Lanka",
    "SD":"Sudan",
    "SR":"Suriname",
    "SS":"South Sudan",
    "SJ":"Svalbard and Jan Mayen",
    "SZ":"Swaziland",
    "SE":"Sweden",
    "CH":"Switzerland",
    "SY":"Syrian Arab Republic",
    "TW":"Taiwan, Province of China",
    "TJ":"Tajikistan",
    "TZ":"Tanzania, United Republic of",
    "TH":"Thailand",
    "TL":"Timor-Leste",
    "TG":"Togo",
    "TK":"Tokelau",
    "TO":"Tonga",
    "TT":"Trinidad and Tobago",
    "TN":"Tunisia",
    "TR":"Turkey",
    "TM":"Turkmenistan",
    "TC":"Turks and Caicos Islands",
    "TV":"Tuvalu",
    "UG":"Uganda",
    "UA":"Ukraine",
    "AE":"United Arab Emirates",
    "GB":"United Kingdom",
    "US":"United States",
    "UM":"United States Minor Outlying Islands",
    "UY":"Uruguay",
    "UZ":"Uzbekistan",
    "VU":"Vanuatu",
    "VE":"Venezuela, Bolivarian Republic of",
    "VN":"Viet Nam",
    "VG":"Virgin Islands, British",
    "VI":"Virgin Islands, U.S.",
    "WF":"Wallis and Futuna",
    "EH":"Western Sahara",
    "YE":"Yemen",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
}